# Generated by Django 2.1 on 2018-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyMed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
