# Generated by Django 2.1 on 2018-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyMed', '0002_doctor_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='selected',
            field=models.BooleanField(),
        ),
    ]
